name: Check labels action
description: |
  This action runs on PR events and verifies that labels are present/absent according to the provided rules.
inputs:
  one-of:
    description: |
      A CSV list of labels regular expression. Exactly one of them must match the PR labels.
    required: true
outputs:
  matched-labels:
    description: |
      A CSV list of labels that have been found on the PR.
runs:
  using: "docker"
  image: Dockerfile
